- src/main/java/io/gravitee/connector/http/HttpConnection.java
gravitee-io/issues#6967
---
- use it directly by updating your project with version: `1.1.1-SNAPSHOT.6967-remove-accept-encoding-client-header`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.1-SNAPSHOT.6967-remove-accept-encoding-client-header/gravitee-connector-http-1.1.1-SNAPSHOT.6967-remove-accept-encoding-client-header.zip)
> fix: let the API Owner choose the Accept-Encoding

- pom.xml
- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
- src/main/resources/schemas/schema-form.json
- src/test/java/io/gravitee/connector/http/HttpConnectorTest.java
gravitee-io/issues#7007
Hi @brasseld, this change was introduced with the "SME". Was this intentional ?
https://github.com/gravitee-io/gravitee-api-management/blob/3.10.x/gravitee-apim-gateway/gravitee-apim-gateway-http/src/main/java/io/gravitee/gateway/http/connector/AbstractConnector.java#L126-L129
> fix: override headers in endpoint configuration

- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
- src/main/resources/schemas/schema-form.json
- src/test/java/io/gravitee/connector/http/HttpConnectorTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7405
---
- use it directly by updating your project with version: `1.1.3-fix-certs-content-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.3-fix-certs-content-SNAPSHOT/gravitee-connector-http-1.1.3-fix-certs-content-SNAPSHOT.zip)
> fix: support binary stores content

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
see https://github.com/gravitee-io/issues/issues/7573
---
- use it directly by updating your project with version: `1.1.4-fix-handle-client-side-connnection-close-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.4-fix-handle-client-side-connnection-close-SNAPSHOT/gravitee-connector-http-1.1.4-fix-handle-client-side-connnection-close-SNAPSHOT.zip)
> fix: handle sse client side connection close

- README.adoc
- pom.xml
- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
see https://github.com/gravitee-io/issues/issues/7739
---
- use it directly by updating your project with version: `2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT/gravitee-connector-http-2.0.0-refactor-use-commong-proxy-options-factory-SNAPSHOT.zip)
> refactor: use common system proxy options factory

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/test/java/io/gravitee/connector/http/HttpConnectionTest.java
- src/test/java/io/gravitee/connector/http/stub/DummyHttpClientRequest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7812
Working on the backward compatibility of HTTP Header, we detected that multivalued headers were not propagated to the backend. Only one value was sent.
**Fix**
This fix simply replace the way we pushing request headers to upstream: we do not rely anymore on HttpHeaders' iterator which returns the first value for a given key, but we copy the collection of value for each key.
---
- use it directly by updating your project with version: `1.1.6-issues-7812-retro-headers-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee- …
> fix: propagate multi value header properly

- src/main/resources/schemas/schema-form.json
The enumeration of the HTTP redirects status code was incomplete
(e.g. the 308 permanent redirect was missing), leading to some
misunderstanding about how the underlying implementation works.
The parameter is forwarded to the Vert.x HTTP client implementation,
which considers any status in the 3xx range as a redirect and handles
it if the `followRedirect` option is set to `true`
---
- use it directly by updating your project with version: `1.1.5-docs-change-redirect-ui-message-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.5-doc …
> fix: make the follow redirects ui message more generic

- pom.xml
- src/main/java/io/gravitee/connector/http/vertx/VertxHttpHeaders.java
- src/test/java/io/gravitee/connector/http/vertx/VertxHttpHeadersTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7930
Add Map capabilities in VertxHttpHeaders implementation as it's used by `gravitee-reporter-elasticsearch` as a map in freemarker template.
---
- use it directly by updating your project with version: `1.1.9-issues-7930-fix-es-headers-reporting-3-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.9-issues-7930-fix-es-headers-reporting-3-SNAPSHOT/gravitee-connector-http-1.1.9-issues-7930-fix-es-headers-reporting-3-SNAPSHOT.zip)
> fix: restore HTTP headers backward compatibility

- pom.xml
- src/main/java/io/gravitee/connector/http/vertx/VertxHttpHeaders.java
- src/test/java/io/gravitee/connector/http/vertx/VertxHttpHeadersTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7812
https://github.com/gravitee-io/issues/issues/8153
Matching implementation done in https://github.com/gravitee-io/gravitee-gateway-api/pull/125
Return null instead of an empty list when getting an undefined header.
Returning an empty list is causing the following EL to be evaluated to `true`:
`{#request.headers['X-Gravitee-No-Present'] != null}`
---
- use it directly by updating your project with version: `1.1.10-7812-bump-connector-api-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector …
> Return null instead of empty list when getting an undefined header

- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
- src/main/java/io/gravitee/connector/http/ws/WebSocketConnection.java
- src/test/java/io/gravitee/connector/http/AbstractHttpConnectorTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/8228
https://github.com/gravitee-io/issues/issues/8324
- Do not consider `ws` as a secure protocol
- Set WS subprotocols based on the `sec-websocket-protocol` header
---
- use it directly by updating your project with version: `1.1.11-fix-websocket-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.11-fix-websocket-SNAPSHOT/gravitee-connector-http-1.1.11-fix-websocket-SNAPSHOT.zip)
> Fix WebSocket connection

- pom.xml
- src/main/java/io/gravitee/connector/http/ws/SwitchProtocolProxyResponse.java
**Issue**
https://github.com/gravitee-io/issues/issues/8253
Jupiter engine with V3 compatibility relies on `ProxyResponse.connected()` to propagate the proxy response to the reactive chain. Since we have introduced an adapter in Jupiter to support websocket in v3 compatibility mode, we need the `connected()` method indicates `true` after the websocket connection occurred with the backend and the backend response indicates to upgrade to websocket (ie: switch protocol).
> fix: make ws proxy response connected

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/main/java/io/gravitee/connector/http/ws/WebSocketConnection.java
- src/main/java/io/gravitee/connector/http/ws/WebSocketFrame.java
**Issue**
https://graviteecommunity.atlassian.net/browse/APIM-137
Just an improvement to avoid copying byte arrays and memory pressure.
---
- use it directly by updating your project with version: `2.0.7-apim-137-jupiter-backpressure-on-post-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.0.7-apim-137-jupiter-backpressure-on-post-SNAPSHOT/gravitee-connector-http-2.0.7-apim-137-jupiter-backpressure-on-post-SNAPSHOT.zip)
> fix: use native buffer to avoid byte array copy

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/main/java/io/gravitee/connector/http/endpoint/HttpClientOptions.java
- src/main/resources/schemas/schema-form.json
- src/test/java/io/gravitee/connector/http/HttpConnectionTest.java
**Issue**
https://github.com/gravitee-io/issues/issues/7935
This allow to get back to the previous behavior mentioned in the issue while keeping the benefit of the fix related to unsupported encoded content.
Here is a summary of the different cases that could occur depending on what has been configured.
| **Case** | **Client request**<br>**Accept-Encoding** | **Server compression enabled** | **Endpoint compression enabled** | **Endpoint propagate client Accept-Encoding header** | **Backend response encoding** | **Client response encoding** |
| --- | --- | --- | --- | --- | --- | --- |
| **1** | _none_ | _no matter_ | false | false | none | **none** |
| **2** | _none_ | _no matter_ | true | false | gzip, deflate | **none** |
| **3** | gzip, deflate | _no matter_ | false | …
> fix: allow to optionally propagate accept-encoding

- src/main/java/io/gravitee/connector/http/HttpConnectorFactory.java
- src/test/java/io/gravitee/connector/http/HttpConnectorFactoryTest.java
**Issue**
NA
Add unit tests for HttpConnectorFactory class to cover the current behavior regarding endpoint and Expression Language
---
- use it directly by updating your project with version: `1.1.12`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/1.1.12/gravitee-connector-http-1.1.12.zip)
> Add unit tests for HttpConnectorFactory class

- src/main/java/io/gravitee/connector/http/HttpConnectorFactory.java
**Issue**
NA
Do not use RxJava stuff for now as it will create a breaking change
---
- use it directly by updating your project with version: `2.0.9-remove-rxjava-stuff-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.0.9-remove-rxjava-stuff-SNAPSHOT/gravitee-connector-http-2.0.9-remove-rxjava-stuff-SNAPSHOT.zip)
> Do not use RxJava stuff for now as it will create a breaking change

- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
**Issue**
gravitee-io/issues#8689
https://gravitee.atlassian.net/browse/APIM-390
Allows to enable websocket frame compression support. The following project shared by one of our community user demonstrate the issue: https://github.com/gianx89/gravitee-websocket-demo
To test the PR, you can start the provided project and import the below api definition.
Then, create a postman websocket test pointing to `ws://localhost:8082/ws`
Once connected, send the following first command:
```
CONNECT
accept-version:1.1,1.0
heart-beat:1000000,1000000
{{NULL_CHAR}}
```
Note: `NULL_CHAR` must be set as an environment variable with postman in order to make it work: `pm.environment.set('NULL_CHAR', '\0');`
Then the following:
```
SUBSCRIBE
id:sub-0
destination:/topic/messages
{{NULL_CHAR}} …
```
> feat: websocket frame compression support

- src/main/resources/schemas/schema-form.json
https://github.com/gravitee-io/issues/issues/8698
https://gravitee.atlassian.net/browse/APIM-415
To validate against oneOf, the given data must be valid against exactly one of the given subschemas.
See https://json-schema.org/understanding-json-schema/reference/combining.html#oneof
It's like a XOR, if it's valid against multiple subschemas then it's reported invalid. 
This was the case when proxy was disabled but system proxy enabled. 
So I strengthen the subschemas related to system proxy.
---
- use it directly by updating your project with version: `2.1.1-8698-fix-proxy-settings-validation-SNAPSHOT`
- download it from Artifactory …
> Update validation spec in API proxy config schema form

- src/main/java/io/gravitee/connector/http/HttpConnection.java
**Issue**
https://github.com/gravitee-io/issues/issues/8956
https://gravitee.atlassian.net/browse/APIM-1149
Revert back to copy byte array instead of relying on underlying `ByteBuf` because it can produce corrupted chunks when activating TLS and requesting in http1.1 (see https://github.com/eclipse-vertx/vert.x/issues/4509)
The optimization can be reintroduced in a later v2.2.0 to be used by APIM 3.21.x since vertx has been upgraded to 4.3.8 which contains a fix.
---
- use it directly by updating your project with version: `2.1.2-apim-1126-fix-tls-chunk-issue-SNAPSHOT`
- download it from Artifactory …
> fix: avoid chunk corruption with tls and http1.1

- README.adoc
- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/test/java/io/gravitee/connector/http/stub/ThrowingOnGoAwayHttpConnection.java
Reapply ByteBuf optimization and bump dependencies
Revert "fix: avoid chunk corruption with tls and http1.1" - commit a5da167.
BREAKING CHANGE: Need Vert.x `4.3.5` or higher due to this issue eclipse-vertx/vert.x#4509
---
- use it directly by updating your project with version: `3.0.0-reapply-bytebuff-optimization-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.0.0-reapply-bytebuff-optimization-SNAPSHOT/gravitee-connector-http-3.0.0-reapply-bytebuff-optimization-SNAPSHOT.zip)
> Reapply ByteBuf optimization and bump dependencies

- .circleci/config.yml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
Following https://gravitee.atlassian.net/browse/APIM-2632.
This reverts commit 44f1a3d1ae9213c6f3745b7174c695cc24e36999.
The goal is to trigger an alpha release in order to make the revert available in the pre-release directory and make the customer able to test the fix.
---
- use it directly by updating your project with version: `3.0.2-revert-buf-optim-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.0.2-revert-buf-optim-SNAPSHOT/gravitee-connector-http-3.0.2-revert-buf-optim-SNAPSHOT.zip)
> fix: revert "reapply ByteBuf optimization"

- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/main/java/io/gravitee/connector/http/grpc/GrpcConnection.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3675
gRPC APIs were sending unexpected headers to gRPC backend:
- a duplicated `Content-Type` header
- the `Host` header
**Additional context**
---
- use it directly by updating your project with version: `3.0.2-apim3675-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.0.2-apim3675-SNAPSHOT/gravitee-connector-http-3.0.2-apim3675-SNAPSHOT.zip)
> fix: prevent sending unexpected headers to gRPC backend

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnector.java
- src/test/java/io/gravitee/connector/http/HttpConnectorTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3776
**Additional context**
---
- use it directly by updating your project with version: `2.1.4-apim3776-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.1.4-apim3776-SNAPSHOT/gravitee-connector-http-2.1.4-apim3776-SNAPSHOT.zip)
> fix: detects websocket connection with multi-value connection header [2.x]

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnector.java
- src/test/java/io/gravitee/connector/http/HttpConnectorTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3776
**Additional context**
---
- use it directly by updating your project with version: `3.0.3-apim3776-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.0.3-apim3776-master-SNAPSHOT/gravitee-connector-http-3.0.3-apim3776-master-SNAPSHOT.zip)
> fix: detects websocket connection with multi-value connection header [master] 

- pom.xml
- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/main/java/io/gravitee/connector/http/endpoint/HttpClientOptions.java
- src/main/java/io/gravitee/connector/http/ws/WebSocketConnection.java
- src/main/resources/schemas/schema-form.json
- src/test/java/io/gravitee/connector/http/HttpConnectorFactoryTest.java
- src/test/java/io/gravitee/connector/http/HttpConnectorTest.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-3776
Add the possibility to configure the Keep-Alive timeout
**New form display**
***HTTP 1.1 & Compression***
***HTTP 1.1 & No compression***
***HTTP 2 & Compression***
***HTTP 2 & No compression***
---
- use it directly by updating your project with version: `2.2.0-apim-3966-configure-keepalive-timeout-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.2.0-apim-3966-configure-keepalive-timeout-SNAPSHOT/gravitee-connector-http-2.2.0-apim-3966-configure-keepalive-tim …
> Configure Keep-alive timeout

- src/main/resources/schemas/schema-form.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-3966
Make keepaliveTimeout not required
---
- use it directly by updating your project with version: `2.2.1-fix-make-keepalivetimeout-not-required-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/2.2.1-fix-make-keepalivetimeout-not-required-SNAPSHOT/gravitee-connector-http-2.2.1-fix-make-keepalivetimeout-not-required-SNAPSHOT.zip)
> make keepaliveTimeout not required

- src/main/resources/schemas/schema-form.json
**Issue**
https://gravitee.atlassian.net/browse/APIM-3966
Make keepaliveTimeout not required
---
- use it directly by updating your project with version: `3.1.1-fix-make-keepalivetimeout-not-required-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.1.1-fix-make-keepalivetimeout-not-required-master-SNAPSHOT/gravitee-connector-http-3.1.1-fix-make-keepalivetimeout-not-required-master-SNAPSHOT.zip)
> make keepaliveTimeout not required - master

- src/main/java/io/gravitee/connector/http/HttpConnection.java
https://gravitee.atlassian.net/browse/APIM-4986
ensure httpClientRequest is not null when there is request content
---
- use it directly by updating your project with version: `3.1.2-APIM-4986-client-request-npe-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.1.2-APIM-4986-client-request-npe-SNAPSHOT/gravitee-connector-http-3.1.2-APIM-4986-client-request-npe-SNAPSHOT.zip)
> fix: ensure httpClientRequest is not null when there is request content

- src/main/java/io/gravitee/connector/http/ws/WebSocketConnection.java
https://gravitee.atlassian.net/browse/APIM-5257
with the current implementation we miss the first “connection” frame sent by socket.io server, the solution is to pause the endpoint request when upgrading the client request, link them together then resume the endpoint websocket.
---
- use it directly by updating your project with version: `4.0.2-APIM-5257-socketio-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/4.0.2-APIM-5257-socketio-master-SNAPSHOT/gravitee-connector-http-4.0.2-APIM-5257-socketio-master-SNAPSHOT.zip)
> fix: pause the endpoint request when upgrading

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/test/java/io/gravitee/connector/http/HttpConnectionTest.java
https://gravitee.atlassian.net/browse/APIM-5231
https://github.com/gravitee-io/issues/issues/9757
When the http connection is upgraded from http1.1 to http2, an empty body is sent, even if the request is a GET.
And in a GET request the CONTENT-LENGTH header does not exist, we must set it to 0.
---
- use it directly by updating your project with version: `3.1.3-apim-5231-fix-http-upgrade-on-get-request-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.1.3-apim-5231-fix-http-upgrade-on-get-request-SNAPSHOT/gravitee-connector-http-3.1.3 …
> Fix HTTP upgrade bug on GET request - 3.1.x

- pom.xml
- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/test/java/io/gravitee/connector/http/HttpConnectionTest.java
https://gravitee.atlassian.net/browse/APIM-5231
https://github.com/gravitee-io/issues/issues/9757
When the http connection is upgraded from http1.1 to http2, an empty body is sent, even if the request is a GET.
And in a GET request the CONTENT-LENGTH header does not exist, we must set it to 0.
---
- use it directly by updating your project with version: `4.0.2-apim-5231-fix-http-upgrade-on-get-request-master-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/4.0.2-apim-5231-fix-http-upgrade-on-get-request-master-SNAPSHOT/gravitee-connec …
> Fix HTTP upgrade bug on GET request - master

- src/main/java/io/gravitee/connector/http/AbstractHttpConnection.java
- src/main/java/io/gravitee/connector/http/HttpConnection.java
https://gravitee.atlassian.net/browse/APIM-8046
cherry pick from https://github.com/gravitee-io/gravitee-connector-http/pull/87
---
- use it directly by updating your project with version: `5.0.0-APIM8046-alpha-cherry-pick-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/5.0.0-APIM8046-alpha-cherry-pick-SNAPSHOT/gravitee-connector-http-5.0.0-APIM8046-alpha-cherry-pick-SNAPSHOT.zip)
> fix: avoid some NPE when connection has failed

- src/main/java/io/gravitee/connector/http/HttpConnection.java
- src/test/java/io/gravitee/connector/http/HttpConnectionTest.java
https://gravitee.atlassian.net/browse/APIM-8304
Create SSL connection for https requests only.
> fix: set SSL for https requests only

- src/main/java/io/gravitee/connector/http/AbstractHttpConnector.java
https://gravitee.atlassian.net/browse/APIM-8624
When we deploy APi during active requests with long read timeout we could block entire Gateway by blocking vert.x-eventloop-thread.
graceful stop is made by the API reactor which tracks the pending requests and apply a graceful delay base on a global gateway config (e.g. api.pending_requests_timeout: 10000)
---
- use it directly by updating your project with version: `3.1.6-APIM-8624-onstop-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/3.1.6-APIM-8624-onstop-SNAPSHOT/gravitee-connecto …
> fix: remove graceful shutdown on stop http connector

- src/main/java/io/gravitee/connector/http/HttpConnection.java
https://gravitee.atlassian.net/browse/APIM-9142
changed reference 'event' to 'exEvent'
---
- use it directly by updating your project with version: `5.0.4-APIM-9142-Bug-in-HttpConnection-exceptionHandlerMaster-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/5.0.4-APIM-9142-Bug-in-HttpConnection-exceptionHandlerMaster-SNAPSHOT/gravitee-connector-http-5.0.4-APIM-9142-Bug-in-HttpConnection-exceptionHandlerMaster-SNAPSHOT.zip)
> fix: changed reference 'event' to 'exEvent'

- src/main/java/io/gravitee/connector/http/HttpConnection.java
https://gravitee.atlassian.net/browse/APIM-9685
This PR avoid an exception linked to this PR https://github.com/gravitee-io/gravitee-api-management/pull/11860
There is some case where the response could have been released before and this causes an NPE.
---
- use it directly by updating your project with version: `5.0.5-fix-status-0-when-emulation-v4-engine-activated-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/connector/gravitee-connector-http/5.0.5-fix-status-0-when-emulation-v4-engine-activated-SNAPSHOT/gravitee-connector-http-5.0.5-fix-status-0-when-emulation-v …
> fix: check if response endHandler is not null before invoking it
